[package]
name = "php-lsp-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Shared types for php-lsp"

[dependencies]
serde = { workspace = true }
lsp-types = { workspace = true }
